### ISSUE TITLE
Research how delayed absorption is typically handled in PK models 

### ISSUE THREAD

**Issue by berghammeraj** [RTIInternational/virtual-opioid-user#13]

**Comment by sandypreiss** [comment]
I was hoping to find some guidance on this in [Lotsch 2005](10.1016/j.jpainsymman.2005.01.012) but it didn't help much. Not sure if that's because he doesn't really discuss this or because I don't have the math skillz to understand a lot of this paper. 

However, generalizing beyond opioids, I found this super helpful chapter on [Pharmacokinetics of Oral Administration](https://accesspharmacy.mhmedical.com/content.aspx?bookid=513&sectionid=41488025). Equation 7.11 is the one we want. It is also very similar to the modified concentration equation that Georgiy added to the WinterSim paper.
